Group.find_or_create_by!(name: "ドラゴンクエストX")
Group.find_or_create_by!(name: "Fortnite")
Group.find_or_create_by!(name: "Apex")
Group.find_or_create_by!(name: "shadowverse")
Group.find_or_create_by!(name: "ファイナルファンタジーXIV")
Group.find_or_create_by!(name: "レインボーシックスシージ")
Group.find_or_create_by!(name: "League of Legends")
Group.find_or_create_by!(name: "ロストアーク")
Group.find_or_create_by!(name: "大乱闘スマッシュブラザーズ")
Group.find_or_create_by!(name: "スプラトゥーン")
Group.find_or_create_by!(name: "桃太郎電鉄")